name: vimeo_likes
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: vladimir.minkin <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  dart_machine: ^0.1.0
  color: any

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.4
